name = "MyProject"
uuid = "9bf6b286-dfbf-4fea-8a03-fdef10a59088"
authors = ["A.Kozlov <forvoxchannel@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Descriptors = "b2dd10be-c0b5-41fc-bf7d-fdb86be5b335"
ExtractMkp = "c0abfc36-1f8e-4183-bc8d-d58e702be582"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FileUnv_jll = "c10d0ea1-10c0-5fab-a796-b821f293b8d8"
FileUtils = "61402b12-eb4b-4f0c-a04f-adfcfe5d14e4"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IBoxAccess = "1607262a-405a-4f9a-89bc-45a61e12db11"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
TimeSamplings = "ed45db17-24e9-469d-8275-17d3d36e28e6"
XMLDict = "228000da-037f-5747-90a9-8195ccbf91a5"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
wfdb_wrapper_jll = "cfa65b43-6878-5963-b59c-e7edc60d5dc9"

[sources]
Descriptors = {url = "https://github.com/IncartStudents/Descriptors.jl"}
ExtractMkp = {url = "https://github.com/IncartStudents/ExtractMkp.jl"}
FileUnv_jll = {url = "https://github.com/a-mikhaylov/FileUnv_jll.jl.git"}
FileUtils = {url = "https://github.com/IncartStudents/FileUtils.jl"}
IBoxAccess = {url = "https://github.com/IncartStudents/IBoxAccess.jl"}
TimeSamplings = {url = "https://github.com/IncartStudents/TimeSamplings.jl"}
wfdb_wrapper_jll = {url = "https://github.com/sairus7/wfdb_wrapper_jll.jl.git"}

[compat]
BenchmarkTools = "1.6.0"
DataFrames = "1.7.0"
DataStructures = "0.18.22"
Descriptors = "1.3.6"
FileUtils = "1.0.3"
PkgTemplates = "0.7.53"
TestItemRunner = "1.1.0"
TestItems = "1.0.0"
YAML = "0.4.14"
